package com.ecommerce.entity;
// Generated 8 Aug, 2017 10:53:27 AM by Hibernate Tools 5.2.3.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.stereotype.Component;


/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "cart", catalog = "e_commerce")
@Component
public class Cart implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private long cartId;
	private Product product;
	private User user;

	public Cart() {
	}

	
	@Id
	@Column(name = "cartId", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	public long getCartId() {
		return this.cartId;
	}

	public void setCartId(long cartId) {
		this.cartId = cartId;
	}


	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "productId", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}
	

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "userId", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}


}
