package com.ecommerce.entity;
// Generated 8 Aug, 2017 10:53:27 AM by Hibernate Tools 5.2.3.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.stereotype.Component;


/**
 * DeliveryAddress generated by hbm2java
 */
@Entity
@Table(name = "deliveryAddress", catalog = "e_commerce")
@Component
public class DeliveryAddress implements Serializable {


	private static final long serialVersionUID = 1L;
	
	private long addressId;
	private User user;
	private String addressType;
	private int pincode;
	private String address;
	

	public DeliveryAddress() {
	}

	@Id
	@Column(name = "addressId", nullable = false , unique = true)
	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	public long getAddressId() {
		return addressId;
	}

	public void setAddressId(long addressId) {
		this.addressId = addressId;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "userId", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "addressType", nullable = false, length = 50)
	public String getAddressType() {
		return this.addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

	@Column(name = "pincode", nullable = false)
	public int getPincode() {
		return this.pincode;
	}

	public void setPincode(int pincode) {
		this.pincode = pincode;
	}

	@Column(name = "address", nullable = false, length = 101)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
