package com.ecommerce.entity;
// Generated 8 Aug, 2017 10:53:27 AM by Hibernate Tools 5.2.3.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.springframework.stereotype.Component;


/**
 * SubCategory generated by hbm2java
 */
@Entity
@Table(name = "subCategory", catalog = "e_commerce")
@Component
public class SubCategory implements Serializable {


	private static final long serialVersionUID = 1L;
	
	private long subcategoryId;
	private Category category;
	private String subCategoryName;
	private String imageUrl;

	/*private long categoryId;*/

	public SubCategory() {
	}


	@Id
	@Column(name = "subcategoryId", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	public long getSubcategoryId() {
		return this.subcategoryId;
	}

	public void setSubcategoryId(long subcategoryId) {
		this.subcategoryId = subcategoryId;
	}
  
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "categoryId", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "subCategoryName", length = 25)
	public String getSubCategoryName() {
		return this.subCategoryName;
	}

	public void setSubCategoryName(String subCategoryName) {
		this.subCategoryName = subCategoryName;
	}

	@Column(name = "imageURL", length = 100)
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	/*@Column(name = "categoryId" , nullable = false)
	public long getCategoryId() {
		return categoryId;
	}

	public void setCategoryId(long categoryId) {
		this.categoryId = categoryId;
	}*/
}
