package com.ecommerce.entity;
// Generated 8 Aug, 2017 10:53:27 AM by Hibernate Tools 5.2.3.Final



import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.stereotype.Component;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "e_commerce")
@Component
public class User implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private long userId;
	private String name;
	private String userName;
	private String password;
	private transient Long mobileno;
	private int primaryaddressId;

	public User() {
	}

	@Id
	@Column(name = "userId" , nullable = false , unique = true)
	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	public long getUserId() {
		return userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "userName", nullable = false, length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "mobileno")
	public Long getMobileno() {
		return this.mobileno;
	}

	public void setMobileno(Long mobileno) {
		this.mobileno = mobileno;
	}

	@Column(name = "primaryaddressId")
	public int getPrimaryaddressId() {
		return this.primaryaddressId;
	}

	public void setPrimaryaddressId(int primaryaddressId) {
		this.primaryaddressId = primaryaddressId;
	}

}
